version: "3.0"
services:
  modbus-payload-converter:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "modbus-payload-converter"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      TYPE: "double-word"
      OFFSET: 0
      FORMAT: "string"
      SWAP: "abcd"
      INPUT_LABEL: "data"
      OUTPUT_LABEL: "output_data"
    ports:
      - 80:80
